### ISSUE TITLE
items are gone when scrolling fast

### ISSUE THREAD

**Issue by bjccoronel** [kapil93/CircularLayoutManager#14]
Hi, i just noticed that if i scroll up too fast to the recyclerview, the items are gone. any idea on this?

**Comment by kapil93** [comment]
Hi, I am not able to recreate it by just swiping faster. How do you recreate it?

**Comment by kapil93** [comment]
Anybody else facing this issue?

**Comment by bjccoronel** [comment]
I am using s7 edge, Nougat.

**Comment by yakovtsova** [comment]
yes, I'm facing this issue

**Comment by yakovtsova** [comment]
My device is Pixel 2

**Comment by artillerymans** [comment]
有谁解决了吗？？？

**Comment by atufkas** [comment]
> Anybody else facing this issue?

Yes, currently investigating...

**Comment by ravikant55** [comment]
> Anybody else facing this issue?

yes, I'm facing this issue

I just make changes from

String[] priceList = {"BOLT", "NUT", "ALLEN", "MS SCREW", "MC SCREW NEW GST", "NYLOCK NUT","STAP", "24 MM BOLT", "14 MM ALLEN", "STUD", "WING NUT", "DOME NUT",};

to

String[] priceList = {"BOLT", "NUT", "ALLEN", "MS SCREW", "NYLOCK NUT","STAP", "24 MM BOLT", "14 MM ALLEN", "STUD", "WING NUT", "DOME NUT", "MC SCREW NEW GST"};

and it's working now.

**Comment by BreimerR** [comment]
Experienced the same issue where if I use too small items i.e image view 24dp and text at 20dp title, and 12dp text the items just exit the view area

![image](https://user-images.githubusercontent.com/25663524/75419308-99bb6780-5946-11ea-8b37-de432db181a9.png)

This happens on scroll not detach views issue

**Comment by kapil93** [comment]
Fixed in the latest version.
