### ISSUE TITLE
Can't click item if there's only item in the recylerview.

### ISSUE THREAD

**Issue by kotlinnewbie** [kapil93/CircularLayoutManager#15]
Hi. If my recyclerview list has only one item in it, I can't click that item. Please help

**Comment by BreimerR** [comment]
![image](https://user-images.githubusercontent.com/25663524/75348174-59f77000-58b3-11ea-841c-2d24675c2244.jpeg)


Can not seem to be able to replicate your issue can you please replicate it and post a stack trace here?

**Comment by kapil93** [comment]
Even though I wasn't able to replicate it, it must've definitely gotten fixed in the latest version.

**Comment by kotlinnewbie** [comment]
Hi!

I need your help urgently.

With this code of yours, I cant scroll the recyclerview to a certain
position using smoothScrollToPosition, scrollTo, smoothScrollToPosition.

Which scroll method can I use to like scroll to bottom for example?


Regards,
Rocky

**Comment by kotlinnewbie** [comment]
I also think because the recyclerview is wrapped around a custom
CircrularLayout. Any workaround?
